### ISSUE TITLE
maker+MPI running slow after a few minutes

### ISSUE THREAD

**Issue by anearman** [Yandell-Lab/maker#16]
Hello!

I am running maker with mpich and no matter what value I put for -n, it begins running on the expected number of threads (e.g. -n 6 runs 24 threads), but once maker reaches either a blast or est2genome search, it drops to 3 threads for the remainder of the run. 

I've installed mpich from source with the shared library configuration, run it successfully with the built-in examples, and checked that maker is configured with mpi successfully (both with ./Build status and that perl Build.PL points to the right 'flavor' of mpi files prior to install). I'm running Ubuntu 22.04LTS on an Intel i9 with 128GB RAM, configured with a 2GB swap. 

Have I missed some critical configuration step?

Thank you!

**Comment by carsonhh** [comment]
maker doesn't parallelize per step (i.e. everything does blast, then everything does exonerate, etc). Rather it parallelizes per chunk (whatever you set max_dna_len=). Each chunk can use a single CPU. What you will see is that some blast's may run or some exonerates, or some other intermediate processes where maker is doing something. But each chunk will not be synchronized with the others and will be doing something different. So you would have to look at the total CPU usage rather than any single process or step. You can test if MPI is working by running 'mpiexec -n <number> maker --help', and you should get a single help message. If you get multiple (equal to number you set) then the communication ring is down. If you want to change the CPU's given to blast, you can set cpus=X inside of maker_opts.ctl. But technically you will then be oversubscribing the system as each chunk will try to use X  CPUs multiplied by the number of active chunks. Note that some schedulers like SLURM may crack down on that type of behavior and throttle your total CPU usage because of that, even if you have a dedicated node. Depending on what flavor of MPI you use, you may want to consider removing environmental variables like OMP_NUM_THREADS or MV2_ENABLE_AFFINITY to stop SLURM from doing this. Also on OpenMPI consider setting --oversubscribe,  --bind-to 'none', and --mca 'btl_openib_want_fork_support'
